---
abstract: 'Administrative utilities for HTGT'
author:
  - 'Ray Miller <rm7@sanger.ac.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTGT-Admin-Utils
requires:
  Const::Fast: 0
  DBI: 0
  Getopt::Long: 0
  Template: 0
  Term::ReadPassword: 0
  strict: 0
  warnings: 0
version: 0.003
